##############################
# Variables you need to change
##############################

vcf: "" # path to the vcf of variants you want counts from
gen: "" # path to the genome fasta file you want
