##############################
# Variables you need to change
##############################

snp_vcf: "" # path to the vcf of variants you want counts from
genome: "" # path to the genome fasta file you want
